### ISSUE TITLE
DIY Linux Router Posts

### ISSUE THREAD

**Issue by jman223** [stephan13360/tutorials#1]
Stephan - Apologies for reaching out this way, but I was unable to find an email for you and wanted to see if it was possible to get access to your "DIY Linux Router" posts? Your [site](https://www.sherbers.de/diy-linux-router-part-1-hardware/) appears to be down.

Thanks
James

**Comment by stephan13360** [comment]
Hi James,

yeah I took it down since I lacked motivation to update it and the underlying software stack.
The linux router posts also no longer described what I was doing on my actually router.
Maybe someday I will add my current configuration to this repository (that is the idea), but no ETA on when this is actually happening. Sorry.

**Comment by jman223** [comment]
No worries. Thanks for the reply.  I currently use a UDM Pro as my edge
router/firewall. I want to replace it with a nftables based firewall that I
can manage from  the command line. I haven't been able to find any good
write ups on this though. Is this what you're doing?

I'm leaning toward running pf on OpenBSD now, because I'm able to find
plenty of examples. Would still rather say with nftables though.

**Comment by stephan13360** [comment]
Yes, I now use nftables.

I have a systemd service:

```
[Unit]
Description=Firewall
Wants=network-pre.target
Before=network-pre.target shutdown.target
Conflicts=shutdown.target
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=true

ExecStart=/usr/sbin/nft -f /usr/local/sbin/firewall.nft
ExecReload=/usr/sbin/nft -f /usr/local/sbin/firewall.nft
ExecStop=/usr/sbin/nft flush ruleset

# capabilities
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_MODULE
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM

[Install]
WantedBy=multi-user.target
```

and a base nft script:

```
#!/usr/sbin/nft -f

flush ruleset

add table inet firewall

add chain inet firewall INPUT { type filter hook input priority filter; policy accept; }
add chain inet firewall FORWARD { type filter hook forward priority filter; policy accept; }
add chain inet firewall MANGLE { type filter hook forward priority mangle; policy accept; }
add chain inet firewall PREROUTING { type nat hook prerouting priority dstnat; policy accept; }
add chain inet firewall POSTROUTING { type nat hook postrouting priority srcnat; policy accept; }

add rule inet firewall INPUT ct state established,related accept
add rule inet firewall INPUT ct state invalid drop
add rule inet firewall FORWARD ct state established,related accept
add rule inet firewall FORWARD ct state invalid drop

add rule inet firewall INPUT iifname lo accept

add rule inet firewall INPUT icmp type echo-request limit rate 5/second accept
add rule inet firewall INPUT icmpv6 type echo-request limit rate 5/second accept
add rule inet firewall INPUT icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-reply, mld-listener-query, mld-listener-report, mld-listener-reduction, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, ind-neighbor-solicit, ind-neighbor-advert, mld2-listener-report } accept

define ip4_local = { 10.10.10.0/23, 10.10.20.0/24, 192.168.178.0/24 }

add rule inet firewall INPUT tcp dport 22 ip saddr $ip4_local accept comment "SSH"

include "/usr/local/etc/firewall/*.nft"

add rule inet firewall INPUT reject
add rule inet firewall FORWARD reject
```

And I can then add additional nft scripts inside /usr/local/etc/firewall/ and reload the service to add more rules.
For example:

```
#!/usr/sbin/nft -f
add rule inet firewall INPUT tcp dport 80 accept comment "http"
add rule inet firewall INPUT tcp dport 443 accept comment "https"
```

So I dont directly manage it through the command line, but maybe this is of interesst for you.

The advantage of having one script with includes is, that you can not fuck up the syntax and leave your firewall half open. If you make a syntax error in one of te scripts and reload the firewall the whole script will fail and nft will not change the running configuration.

**Comment by jman223** [comment]
Thanks, Stephan.
